# pubspec.yaml
name: rocket_notes_ai
description: AI-powered note-taking app with NFC support

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # NFC
  flutter_nfc_kit: ^3.3.1
  nfc_manager: ^3.3.0

  # Deep Links
  app_links: ^3.4.5

  # UI
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  flutter_quill: ^9.3.21

  # Device Info
  package_info_plus: ^4.2.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # File Operations
  path_provider: ^2.1.1
  file_picker: ^6.1.1

  # Sharing
  share_plus: ^7.2.1

  # URL Launcher
  url_launcher: ^6.2.1

  # Web App dependencies
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  uuid: ^4.0.0

  # Date Formatting
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
