# pubspec.yaml
name: pensieve
description: AI-powered note-taking app with NFC support

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^16.2.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # JavaScript interop for web
  # js: ^0.6.7  # Discontinued package, removed

  # NFC
  flutter_nfc_kit: ^3.3.1

  # Deep Links
  app_links: ^6.4.1

  # UI
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  flutter_quill: 11.4.2
  flutter_keyboard_visibility: ^6.0.0

  # Device Info
  package_info_plus: ^8.3.1

  # JSON Serialization
  json_annotation: ^4.9.0

  # File Operations
  path_provider: ^2.1.1
  file_picker: ^10.3.2

  # Equality and immutability helpers
  equatable: ^2.0.5

  # Sharing
  share_plus: ^11.1.0

  # Image Processing (Web Compatible)
  image_picker: ^1.0.4
  image: ^4.1.3

  # Camera Support
  camera: ^0.11.2
  photo_view: ^0.15.0
  permission_handler: ^12.0.1

  # Biometric Authentication
  local_auth: ^2.1.6
  
  # Voice Recording (moved to end of dependencies)
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.3
  
  # Encryption
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # App Rating
  in_app_review: ^2.0.9
  
  # Path utilities
  path: ^1.8.3

  # Google ML Kit OCR (Compatible versions)
  google_ml_kit: ^0.20.0

  # HTTP & API
  dio: ^5.3.2

  # Firebase Integration
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # Additional Firebase services for family features
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.1.4

  # Reactive programming for real-time data
  rxdart: ^0.28.0

  # URL Launcher
  url_launcher: ^6.2.1

  # Web App dependencies
  http: ^1.1.0
  connectivity_plus: ^6.1.5
  uuid: ^4.0.0

  # Date Formatting
  intl: ^0.20.2
  record: ^6.1.1

  # Speech to Text and Voice Processing
  speech_to_text: ^7.0.0
  flutter_tts: ^4.1.0

  # AI and OpenAI Integration
  openai_dart: ^0.3.0
  
  # WebSocket for real-time collaboration
  web_socket_channel: 3.0.3

  # Export and PDF generation
  pdf: ^3.10.4
  printing: ^5.11.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: ^1.24.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
